name: Request to add a new press release or press link
description: Use this issue to request to add a new press release or press link to Calitp.org
title: "New press request"
labels:
  - content
  - press
body:
  - type: input
    id: title
    validations:
      required: true
    attributes:
      label: Title
      description: The title is used in list views on the home page and [https://calitp.org/press](https://calitp.org/press)
  - type: input
    id: heading
    attributes:
      label: Heading (optional)
      description: Optional heading if different from the title, used on the page for this press release
  - type: input
    id: link
    validations:
      required: true
    attributes:
      label: Asset URL
      description: "The URL of the resource: link to Google Drive content of press release, or external link to a press item outside of Cal-ITP"
  - type: dropdown
    id: tag
    validations:
      required: true
    attributes:
      label: Tag
      description: What tag is this press item in?
      multiple: false
      options:
        - Contactless payments
        - Benefits
        - GTFS
  - type: dropdown
    id: date_year
    validations:
      required: true
    attributes:
      label: Date - Year
      description: The date is used for both internal and external press releases.
      multiple: false
      options:
        - 2023
        - 2022
        - 2021
        - 2020
  - type: dropdown
    id: date_month
    validations:
      required: true
    attributes:
      label: Date - Month
      description: The date is used for press releases.
      multiple: false
      options:
        - "01"
        - "02"
        - "03"
        - "04"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
  - type: input
    id: location
    validations:
      required: true
    attributes:
      label: Location
      description: The location is used for press releases. The default is Sacramento, CA
      placeholder: Sacramento, CA
